[package]
name = "diagram-svg-preprocessor"
version = "0.1.0"
authors = ["Connell <connellr023@gmail.com>"]
edition = "2021"

[dependencies]
anyhow = "1.0.91"
regex = "1.11.1"
serde = { version = "1.0.213", features = ["derive"] }
serde_json = "1.0.132"
